apiVersion: v1
kind: Service
metadata:
  name: uploader-service
  namespace: exam-samuel
spec:
  type: NodePort
  selector:
    app: uploader
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081

# Service je Kubernetes objekt, ktorý definuje spôsob, ako sú pody dostupné
# v sieti, či už v rámci klastra alebo zvonku. Umožňuje smerovať sieťovú prevádzku
# na skupinu podov na základe štítkov (labels). Tento Service s názvom
# 'uploader-service' v namespace 'exam-samuel' je typu NodePort, čo znamená,
# že vystavuje aplikáciu na konkrétnom porte (30081) na všetkých uzloch klastra.
# Smeruje prevádzku z portu 80 na port 80 podov označených štítkom 'app: uploader',
# čím umožňuje prístup k webovej aplikácii (napr. PHP uploader) cez IP uzla a port 30081.